name: My Open Catalogi Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'master'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:              
      - name: Create or Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@1.0.1
        with:
          opencatalogi: true
      - name: Create an Open Catalogi page
        uses: OpenCatalogi/opencatalogi-action@1.1.8
        with:
          github_repository_name_as_prefix: false
          nl_design_theme_classname: 'dimpact-theme'
          pull_from_branche: 'development'
          start_page: 'https://github.com/Dimpact-Samenwerking/Dimpact-Open-Catalogi/blob/main/README.md'
          footer_content: 'https://raw.githubusercontent.com/Dimpact-Samenwerking/Dimpact-Open-Catalogi/main/FooterContent.json'
          navbar_content: 'https://raw.githubusercontent.com/Dimpact-Samenwerking/Dimpact-Open-Catalogi/main/HeaderContent.json'
          navbar_logo: 'false'
          favicon_logo: 'data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABILAAASCwAAAAAAAAAAAAB7PgT/kV4u/5RiM/+UYjP/lGIz/5RiM/+UYjP/lGIz/5RiM/+UYjP/lGIz/5RiM/+UYjP/lGIz/5JgMP99QAf/ilQf/6qDXf+PWy//kmAv/5JgL/+SYC//kl8v/4xXJP+LViP/kl8u/5JgL/+SYC//kmAv/49bL/+ogFr/jloo/4xXI/+YaDr/cS8A/3U1AP91NQD/dTUA/3c3AP+cbkP/n3JI/3k6AP91NAD/dTUA/3U1AP9xLwD/lGIy/49cK/+LViL/mms+/3U1AP95OwD/eTsA/3g5AP99QQj/9/Pv//////+ESxT/dzcA/3k7AP95OwD/dTUA/5ZmN/+PWyr/i1Yi/5prPv91NQD/eTsA/3k7AP94OQD/fUEI//Hr5f/59/T/g0oT/3c3AP95OwD/eTsA/3U1AP+WZjf/j1sq/4tWIv+aaz7/dTUA/3k7AP95OwD/eDkA/31BCP/x6uT/+fbz/4NKE/93NwD/eTsA/3k7AP91NQD/lmY3/49bKv+LViL/mms+/3U1AP95OwD/eTsA/3g5AP99QQj/8erk//n28/+DShP/dzcA/3k7AP95OwD/dTUA/5ZmN/+PWyr/i1Yi/5prPv91NQD/eTsA/3k7AP94OQD/fUEI//Hq5P/59vP/g0oT/3c3AP95OwD/eTsA/3U1AP+WZjf/j1sq/4tWIv+aaz7/dTUA/3k7AP95OwD/eDkA/31BCP/x6uT/+fbz/4NKE/93NwD/eTsA/3k7AP91NQD/lmU2/5BcK/2LViL/mms+/3U1AP95OwD/eTsA/3g5AP99QQn/+fXy//////+ESxT/dzcA/3k7AP95OwD/dDMA/59zSP+LVSHni1Yi/5prPv91NQD/eTsA/3k7AP95OgD/ez4E/7iYcP+9n3f/f0MK/3g5AP95OwD/eToA/3s9Bf+rhF7/ejsEqItWIv+aaz7/dTUA/3k7AP95OwD/eTsA/3k8AP9lD2X/Ywtw/3k6Av95PAD/eTsA/3MxAP+cbkL/lWQ2/nU1ADyLViL/mms+/3U1AP95OwD/eTsA/3k7AP96PAH/aA+Z/2YLp/95OwT/eTsA/3MyAP+OWin/o3dO/6BzSZiOWScAjFcj/5hoOf9xLgD/dTUA/3U1AP91NQD/dTUA/3QzAP90MwD/dDQA/31ADP+ecUn/onZP/5tsQLrz7ugKj1spAIlSHf+shV//k2E3/5ZlN/+WZTf/lmU3/5ZlN/+WZTX/lmY3/6J2UP+qgl//k2E59qN4UpDw6eMI9/PvAIpTIAB6PQP/jVgm/5BdLP+QXSz/kF0s/5BdLP+QXSz/kF0s/5BdLPuIURzhdzgAnnY2ADmQXSwAjlooAItVIgB8PwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAwAAAA8AAA=='
          jumbotron_title: "Dimpact Catalogi"
          jumbotron_description: "Alleen door onze collectieve wijsheid te bundelen, we de grenzen van mogelijkheden kunnen verleggen."
          jumbotron_searchform: "true"
